apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  IMAGES: {{ .Values.configMap.images }}
  DAEMONSET_NAME: "kubernetes-image-puller"
  CACHING_INTERVAL_HOURS: "{{ .Values.configMap.cachingIntervalHours }}"
  NAMESPACE: {{ .Release.Namespace }}
  CACHING_MEMORY_REQUEST: {{ .Values.configMap.cachingMemoryRequest }}
  CACHING_MEMORY_LIMIT:  {{ .Values.configMap.cachingMemoryLimit }}
  NODE_SELECTOR: "{{ .Values.configMap.nodeSelector }}"
